(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DEG=['1','♭2','2','♭3','3','4','♯4','5','♭6','6','♭7','7'];
const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const DATA={
'メジャー（Ionian）':{summary:'最も基準になる長音階。明るさと安定感があり、多くのポップスやロックの土台になる。',why:'3度が長3度なので明るく、7度が導音としてルートへ半音で解決するため、調性感が強く出る。',feature:['3','7'],avoid:'IVmaj7上で4度を長く伸ばすと3度と半音でぶつかる場合がある。',phrase:'1→2→3→5、5→6→7→1のように、3度と7度を意識するとメジャーらしさが出やすい。',chord:'Imaj7、ii7、IVmaj7、V7など。特にV7→Iで強い解決感を作れる。',tip:'まずこの音階を基準に、他スケールで「どの音が変わったか」を比較すると理解しやすい。'},
'ナチュラル・マイナー（Aeolian）':{summary:'自然な短調の基準。暗さ、哀愁、落ち着きを作りやすい。',why:'♭3がマイナー感を決め、♭6と♭7が柔らかく閉じた響きを作る。',feature:['♭3','♭6','♭7'],avoid:'強いV7→iを作りたい場合は7度を上げたハーモニックマイナーの方が向く。',phrase:'1→♭3→4→5、5→♭7→♭6→5のように♭3・♭6を意識すると哀愁が出る。',chord:'Im7、♭IIImaj7、IVm7、♭VImaj7、♭VII7など。',tip:'メジャーと比べるなら3・6・7度が半音低い点を見ると一気に理解しやすい。'},
'ハーモニック・マイナー':{summary:'自然短音階の7度を上げ、短調でも強いドミナント解決を作れる音階。',why:'7度がルートの半音下になることで導音が生まれ、V7→iの引力が強くなる。',feature:['♭3','♭6','7'],avoid:'♭6と7の間が増2度になるため、旋律で使うと強い異国感が出る。',phrase:'5→♭6→7→1を使うと劇的な短調感が出る。',chord:'Im(maj7)、IVm7、V7、VImaj7など。',tip:'自然短音階との違いは「♭7が7になる」一点をまず見る。'},
'メロディック・マイナー（上行）':{summary:'短調の♭3を残しながら、6度と7度を上げた洗練されたマイナー音階。',why:'♭3で短調感を保ちつつ、6・7度が明るさと滑らかな上行感を加える。',feature:['♭3','6','7'],avoid:'クラシックとジャズでは扱い方が異なるため、このビューアでは上行形として考える。',phrase:'1→2→♭3→5→6→7→1で、暗さと明るさの混ざった響きを確認できる。',chord:'Im(maj7)、IIm7、IV7など。派生モードも多い。',tip:'ドリアンとの違いは7度、ハーモニックマイナーとの違いは6度。'},
'ドリアン':{summary:'マイナー系なのに6度がナチュラルで、暗すぎず前向きな響きを持つモード。',why:'♭3でマイナー感を作りながら、6度が明るさと抜け感を加える。',feature:['♭3','6','♭7'],avoid:'6度を使わないとナチュラルマイナーとの差が分かりにくくなる。',phrase:'1→♭3→4→5→6→5、または♭7→6→5を使うとドリアンらしさが出る。',chord:'Im7、IIm7、IV7。特にIm7とIV7の往復が分かりやすい。',tip:'ナチュラルマイナーと比較して「♭6→6」の変化を指板で探すのがおすすめ。'},
'フリジアン':{summary:'♭2が最大の特徴。暗さに加えて強い緊張感と異国感を持つ。',why:'ルートの半音上に♭2があるため、1と♭2の半音関係が非常に強く聞こえる。',feature:['♭2','♭3','♭7'],avoid:'♭2を長く鳴らすとかなり強い緊張になるので、意図して使うと効果的。',phrase:'1↔♭2を往復したあと♭3→1へ戻すと特徴がすぐ分かる。',chord:'Im7、♭IImaj7。Iと♭IIの往復も典型的。',tip:'まずルートのすぐ隣にある♭2だけ探すと、指板上でモードの個性が見える。'},
'リディアン':{summary:'メジャー系で最も浮遊感が強いモード。♯4が幻想的な響きを作る。',why:'メジャーの明るさに♯4が加わり、通常の4度よりもルートや3度とぶつかりにくい。',feature:['3','♯4','7'],avoid:'♯4を使わないと普通のメジャーとほぼ同じに聞こえやすい。',phrase:'1→3→♯4→5、7→♯4→3のように♯4を目立たせる。',chord:'Imaj7、II7。Imaj7上で♯11として使うとリディアン感が強い。',tip:'メジャーとの比較で「4→♯4」だけ色分けすると違いが一発で分かる。'},
'ミクソリディアン':{summary:'メジャーの明るさを持ちながら♭7で開放感とブルージーさが出るモード。',why:'3度は長3度なので明るいが、7度が導音ではなく♭7なので解決圧が弱まり、ルーズな響きになる。',feature:['3','♭7'],avoid:'7度をナチュラルにするとメジャーへ戻るので、♭7を意識する。',phrase:'1→3→5→♭7→5、または♭7→6→5。',chord:'I7、♭VIImaj7。I7を主和音として長く保てる。',tip:'メジャーと比較して「7→♭7」を見るだけで性格の違いが分かる。'},
'ロクリアン':{summary:'♭2と♭5を持つ最も不安定なチャーチモード。m7♭5上で重要。',why:'ルートに対して完全5度がなく♭5になるため、主和音自体に強い不安定感がある。',feature:['♭2','♭3','♭5'],avoid:'ルートを安定した着地点として感じにくいので、長く停滞させると緊張が続く。',phrase:'1→♭2→♭3→♭5、または♭5→4→♭3→1。',chord:'Im7♭5、♭IImaj7。ジャズのiiø7でよく関連する。',tip:'まず♭5を強調して、通常のマイナースケールとの差を確認する。'},
'メジャー・ペンタトニック':{summary:'メジャースケールから4度と7度を省いた5音音階。濁りが少なく扱いやすい。',why:'半音衝突しやすい4度・7度を省くことで、コードに対して外れにくい。',feature:['2','3','6'],avoid:'音数が少ないので同じ形だけ弾くと単調になりやすい。リズムや音域で変化を付ける。',phrase:'1→2→3→5→6→5、3→2→1。',chord:'I、IV、Vを中心に幅広く合わせやすい。',tip:'まずルート・3度・6度を着地点として使うと明るいメロディになりやすい。'},
'マイナー・ペンタトニック':{summary:'マイナー演奏の定番となる5音音階。ロックやブルースの核。',why:'♭3と♭7がマイナー／ブルース感を作り、半音の強い衝突が少ない。',feature:['♭3','4','♭7'],avoid:'形だけ覚えると同じフレーズになりやすいので、ルート位置と度数を把握する。',phrase:'1→♭3→4→5→♭7→5、♭7→5→4→♭3→1。',chord:'Im、ブルース進行、ロックのパワーコード上で使いやすい。',tip:'「ボックス形」だけでなく、各音が何度なのか表示を切り替えて覚えると応用しやすい。'},
'リディアン・ドミナント':{summary:'リディアンの♯4とミクソリディアンの♭7を合わせた、明るくモダンなドミナント系スケール。',why:'長3度と♭7でドミナント感を作り、♯4が♯11として独特の浮遊感を加える。',feature:['3','♯4','♭7'],avoid:'通常のV7上では♯11の響きが強いので、コードとの関係を確認して使う。',phrase:'3→♯4→5→♭7、または1→♯4→3。',chord:'7(♯11)、subV7など。',tip:'ミクソリディアンとの違いは4→♯4。比較モードが特に有効。'},
'フリジアン・ドミナント':{summary:'♭2と長3度が同居する強烈なドミナント系スケール。',why:'フリジアン的な♭2と、ドミナントを決める長3度が同時に鳴るため異国感が強い。',feature:['♭2','3','♭6'],avoid:'♭2と3を強調しすぎると非常に濃い響きになるため、フレーズの山場で使うと効果的。',phrase:'1→♭2→3→5、♭6→5→3→1。',chord:'V7(♭9)系。ハーモニックマイナー第5モードとして使われる。',tip:'フリジアンとの違いは♭3→3。そこだけ比較すると分かりやすい。'},
'アルタード':{summary:'ドミナント7thに使える強いテンションを集めたスケール。解決直前の緊張作りに強い。',why:'♭9・♯9・♭5/♯11・♭13相当の音を含み、V7上で最大級の緊張を作る。',feature:['♭2','♭3','♯4','♭6','♭7'],avoid:'トニック上で安定して使う音階ではなく、基本的にはドミナントからの解決を前提に考える。',phrase:'♭9→1、♯9→3、♭13→5など、テンションからコードトーンへ解決する動きを意識する。',chord:'V7alt。特にV7→I / V7→i。',tip:'単体で覚えるより「どのテンションがどこへ解決するか」で覚えると実戦的。'}
};
function intervals(){return $$('#scaleTable tbody tr').map(tr=>Number(tr.lastElementChild?.textContent)).filter(Number.isFinite)}
function note(root,semi){return NOTES[(NOTES.indexOf(root)+semi+12)%12]}
function degrees(vals){return vals.map(v=>DEG[v]).join(' ・ ')}
function notes(root,vals){return vals.map(v=>note(root,v)).join(' ・ ')}
function fallback(name,vals){const altered=vals.filter(v=>![0,2,4,5,7,9,11].includes(v));return {summary:`${name}は${vals.length}音で構成されるスケール。構成度数とルートとの距離を見ると性格を把握しやすい。`,why:altered.length?`メジャースケールと比べると ${altered.map(v=>DEG[v]).join('・')} が大きな違いになる。`:'半音・全音の並び方と、どの音を着地点にするかで響きが決まる。',feature:(altered.length?altered:vals.filter(v=>v!==0).slice(0,3)).map(v=>DEG[v]),avoid:'コード上で長く伸ばす音は、コードトーンとの半音衝突を耳で確認して選ぶ。',phrase:'ルートから特徴音へ進み、最後にルートまたはコードトーンへ戻すと響きを確認しやすい。',chord:'選択したコードの構成音と共通する音を軸にし、特徴音を色として加える。',tip:'比較モードでメジャーまたはマイナー系スケールと比べると違いを把握しやすい。'}}
function render(){const base=$('#scaleLearningCard');if(!base)return;let pro=$('#scaleExplanationPro');if(!pro){pro=document.createElement('section');pro.id='scaleExplanationPro';pro.className='scale-explanation-pro';base.insertAdjacentElement('afterend',pro)}const name=$('#scaleSelect')?.value||'',root=$('#keySelect')?.value||'C',vals=intervals(),d=DATA[name]||fallback(name,vals),feat=(d.feature||[]).join('・');pro.innerHTML=`<div class="exp-head"><div><span>DEEP EXPLANATION</span><h2>${root} ${name} を理解する</h2><p>${d.summary}</p></div><div class="exp-key"><small>特徴</small><b>${feat||'構成音の間隔'}</b></div></div><div class="exp-grid"><article><h3>① なぜこの響きになる？</h3><p>${d.why}</p></article><article><h3>② 構成音</h3><p><b>度数：</b>${degrees(vals)}</p><p><b>音名：</b>${notes(root,vals)}</p></article><article><h3>③ 指板で見るポイント</h3><p>赤いルートを基準に、<b>${feat||'特徴音'}</b>の位置を探そう。まず1か所だけ覚えて、同じ音を別弦でも探すとポジションがつながる。</p></article><article><h3>④ フレーズの作り方</h3><p>${d.phrase}</p></article><article><h3>⑤ 合わせやすいコード</h3><p>${d.chord}</p></article><article><h3>⑥ 注意する音</h3><p>${d.avoid}</p></article></div><div class="exp-practice"><div><small>30秒練習</small><b>ルート → 特徴音 → ルート</b><p>指板上で3か所探して往復。次に表示を「度数」に変えて同じ位置を確認。</p></div><div><small>次にやること</small><b>${d.tip}</b></div></div>`}
function install(){if($('#scaleExplanationPro'))return;const st=document.createElement('style');st.textContent=`.scale-explanation-pro{margin-top:16px;padding:20px;border:1px solid var(--border);border-radius:18px;background:var(--paper);box-shadow:var(--shadow)}.exp-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.exp-head span{font-size:.62rem;font-weight:900;letter-spacing:.14em;color:#8b6f47}.exp-head h2{margin:4px 0 7px;font-size:1.18rem}.exp-head p{max-width:680px;margin:0;color:var(--muted);font-size:.83rem;line-height:1.7}.exp-key{min-width:150px;padding:10px 12px;border-radius:13px;background:#f5efe6}.exp-key small,.exp-key b{display:block}.exp-key small{color:#8b6f47;font-weight:900;font-size:.66rem}.exp-key b{margin-top:3px;font-size:.82rem}.exp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px}.exp-grid article{padding:13px;border:1px solid var(--border);border-radius:14px;background:#faf8f4}.exp-grid h3{margin:0 0 6px;font-size:.82rem}.exp-grid p{margin:4px 0;font-size:.77rem;line-height:1.65}.exp-practice{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.exp-practice>div{padding:13px;border-radius:14px;background:#eef4ff}.exp-practice small,.exp-practice b{display:block}.exp-practice small{color:#2563eb;font-size:.65rem;font-weight:900}.exp-practice b{margin-top:3px;font-size:.82rem}.exp-practice p{margin:5px 0 0;font-size:.75rem;line-height:1.55}html[data-theme=dark] .scale-explanation-pro{background:#201e1b;border-color:#514a42}html[data-theme=dark] .exp-grid article{background:#2b2824;border-color:#514a42}html[data-theme=dark] .exp-key{background:#342d25}html[data-theme=dark] .exp-practice>div{background:#172554}@media(max-width:680px){.scale-explanation-pro{padding:15px}.exp-head{display:block}.exp-key{margin-top:10px}.exp-grid,.exp-practice{grid-template-columns:1fr}}`;document.head.appendChild(st);render();['keySelect','genreSelect','scaleSelect','instrumentSelect'].forEach(id=>$('#'+id)?.addEventListener('change',()=>setTimeout(render,0)));$$('.tension').forEach(x=>x.addEventListener('change',()=>setTimeout(render,0)));$('#tensionClearBtn')?.addEventListener('click',()=>setTimeout(render,0))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(install,30)):setTimeout(install,30);
})();