(()=>{
const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const DEG=['1','b2','2','b3','3','4','#4','5','b6','6','b7','7'];
const SCALES={
'メジャー（Ionian）':[0,2,4,5,7,9,11],'メジャー・ペンタトニック':[0,2,4,7,9],'ブルース・メジャー':[0,2,3,4,7,9],'リディアン・ペンタトニック':[0,2,4,6,9],'ドミナント・ペンタトニック':[0,2,4,7,10],
'ナチュラル・マイナー（Aeolian）':[0,2,3,5,7,8,10],'ハーモニック・マイナー':[0,2,3,5,7,8,11],'メロディック・マイナー（上行）':[0,2,3,5,7,9,11],'マイナー・ペンタトニック':[0,3,5,7,10],'ブルース・マイナー':[0,3,5,6,7,10],'マイナー6ペンタトニック':[0,3,5,7,9],
'ドリアン':[0,2,3,5,7,9,10],'フリジアン':[0,1,3,5,7,8,10],'リディアン':[0,2,4,6,7,9,11],'ミクソリディアン':[0,2,4,5,7,9,10],'ロクリアン':[0,1,3,5,6,8,10],
'ドリアン♭2':[0,1,3,5,7,9,10],'リディアン・オーギュメント':[0,2,4,6,8,9,11],'リディアン・ドミナント':[0,2,4,6,7,9,10],'ミクソリディアン♭6':[0,2,4,5,7,8,10],'ロクリアン♮2':[0,2,3,5,6,8,10],'アルタード':[0,1,3,4,6,8,10],
'ロクリアン♮6':[0,1,3,5,6,9,10],'アイオニアン・オーギュメント':[0,2,4,5,8,9,11],'ドリアン#4':[0,2,3,6,7,9,10],'フリジアン・ドミナント':[0,1,4,5,7,8,10],'リディアン#2':[0,3,4,6,7,9,11],'ウルトラ・ロクリアン':[0,1,3,4,6,8,9],
'ハーモニック・メジャー':[0,2,4,5,7,8,11],'ドリアン♭5':[0,2,3,5,6,9,10],'フリジアン♭4':[0,1,3,4,7,8,10],'リディアン♭3':[0,2,3,6,7,9,11],'ミクソリディアン♭2':[0,1,4,5,7,9,10],
'ダブル・ハーモニック・メジャー':[0,1,4,5,7,8,11],'ハンガリアン・マイナー':[0,2,3,6,7,8,11],'ハンガリアン・メジャー':[0,3,4,6,7,9,10],'ルーマニアン・マイナー':[0,2,3,6,7,9,10],'スパニッシュ・ジプシー':[0,1,4,5,7,8,10],
'ホールトーン':[0,2,4,6,8,10],'ディミニッシュ（H-W）':[0,1,3,4,6,7,9,10],'ディミニッシュ（W-H）':[0,2,3,5,6,8,9,11],'オーギュメント':[0,3,4,7,8,11],'クロマティック':[0,1,2,3,4,5,6,7,8,9,10,11],
'ベバップ・ドミナント':[0,2,4,5,7,9,10,11],'ベバップ・メジャー':[0,2,4,5,7,8,9,11],'ベバップ・ドリアン':[0,2,3,4,5,7,9,10],'ベバップ・ナチュラルマイナー':[0,2,3,5,7,8,9,10],'ベバップ・ハーモニックマイナー':[0,2,3,5,7,8,10,11],
'ネアポリタン・メジャー':[0,1,3,5,7,9,11],'ネアポリタン・マイナー':[0,1,3,5,7,8,11],'エニグマティック':[0,1,4,6,8,10,11],'プロメテウス':[0,2,4,6,9,10],'トリトーン':[0,1,4,6,7,10],
'律音階':[0,2,5,7,9],'呂音階':[0,2,4,7,9],'都節音階':[0,1,5,7,8],'民謡音階':[0,3,5,7,10],'琉球音階':[0,4,5,7,11],'雲井音階':[0,2,3,7,9],'平調子':[0,2,3,7,8],'岩戸音階':[0,1,5,6,10],'陰音階':[0,1,5,7,10],'ヨナ抜き長音階':[0,2,4,7,9],'ヨナ抜き短音階':[0,2,3,7,8],
'エジプシャン':[0,2,5,7,10],'ヒンドゥー':[0,2,4,5,7,8,10],'ペルシアン':[0,1,4,5,6,8,11],'アラビック':[0,2,4,5,6,8,10],'バリニーズ':[0,1,3,7,8],'チャイニーズ':[0,4,6,7,11],'モンゴリアン':[0,2,4,7,9],'インド・トーディー':[0,1,3,6,7,8,11]};
const GENRES={
'メジャー系':['メジャー（Ionian）','メジャー・ペンタトニック','ブルース・メジャー','リディアン・ペンタトニック','ドミナント・ペンタトニック'],
'マイナー系':['ナチュラル・マイナー（Aeolian）','ハーモニック・マイナー','メロディック・マイナー（上行）','マイナー・ペンタトニック','ブルース・マイナー','マイナー6ペンタトニック'],
'チャーチモード':['ドリアン','フリジアン','リディアン','ミクソリディアン','ロクリアン'],
'メロディックマイナー・モード':['ドリアン♭2','リディアン・オーギュメント','リディアン・ドミナント','ミクソリディアン♭6','ロクリアン♮2','アルタード'],
'ハーモニックマイナー・モード':['ロクリアン♮6','アイオニアン・オーギュメント','ドリアン#4','フリジアン・ドミナント','リディアン#2','ウルトラ・ロクリアン'],
'ハーモニック系':['ハーモニック・メジャー','ドリアン♭5','フリジアン♭4','リディアン♭3','ミクソリディアン♭2','ダブル・ハーモニック・メジャー','ハンガリアン・マイナー','ハンガリアン・メジャー','ルーマニアン・マイナー','スパニッシュ・ジプシー'],
'ジャズ・対称音階':['ホールトーン','ディミニッシュ（H-W）','ディミニッシュ（W-H）','オーギュメント','クロマティック'],
'ビバップ系':['ベバップ・ドミナント','ベバップ・メジャー','ベバップ・ドリアン','ベバップ・ナチュラルマイナー','ベバップ・ハーモニックマイナー'],
'現代・人工音階':['ネアポリタン・メジャー','ネアポリタン・マイナー','エニグマティック','プロメテウス','トリトーン'],
'日本音階':['律音階','呂音階','都節音階','民謡音階','琉球音階','雲井音階','平調子','岩戸音階','陰音階','ヨナ抜き長音階','ヨナ抜き短音階'],
'民族・エキゾチック':['エジプシャン','ヒンドゥー','ペルシアン','アラビック','バリニーズ','チャイニーズ','モンゴリアン','インド・トーディー']};
const INST={guitar:{name:'ギター',icon:'🎸',tuning:['E','A','D','G','B','E'],frets:12,info:'標準チューニング E A D G B E / 12フレット'},bass:{name:'ベース',icon:'🎸',tuning:['E','A','D','G'],frets:12,info:'4弦ベース標準チューニング E A D G / 12フレット'},ukulele:{name:'ウクレレ',icon:'🪕',tuning:['G','C','E','A'],frets:12,info:'ウクレレ標準チューニング G C E A / 12フレット'},piano:{name:'ピアノ',icon:'🎹',info:'ピアノ鍵盤 / 2オクターブ表示'}};
const TENSION={b9:1,'9':2,'#9':3,'11':5,'#11':6,b13:8,'13':9};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],mod=n=>(n%12+12)%12,svgEl=n=>document.createElementNS('http://www.w3.org/2000/svg',n);
function opt(v){const o=document.createElement('option');o.value=o.textContent=v;return o}
function initOptions(){NOTES.forEach(n=>$('#keySelect').appendChild(opt(n)));Object.keys(GENRES).forEach(n=>$('#genreSelect').appendChild(opt(n)));$('#keySelect').value='C';$('#genreSelect').value='メジャー系';fillScales()}
function fillScales(){const s=$('#scaleSelect');s.innerHTML='';(GENRES[$('#genreSelect').value]||[]).forEach(n=>s.appendChild(opt(n)))}
function selected(){const base=SCALES[$('#scaleSelect').value]||SCALES['メジャー（Ionian）'];const extra=$$('.tension:checked').map(x=>TENSION[x.value]);return [...new Set([...base,...extra])].sort((a,b)=>a-b)}
function circle(x,y,r,fill){const e=svgEl('circle');Object.entries({cx:x,cy:y,r,fill}).forEach(([k,v])=>e.setAttribute(k,v));return e}
function line(x1,y1,x2,y2,stroke,w=1){const e=svgEl('line');Object.entries({x1,y1,x2,y2,stroke,'stroke-width':w}).forEach(([k,v])=>e.setAttribute(k,v));return e}
function text(x,y,v,size=15){const e=svgEl('text');Object.entries({x,y,'font-size':size,'text-anchor':'middle','dominant-baseline':'middle','font-weight':'700'}).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=v;return e}
function labelFor(pitch,root,mode){if(mode==='notes')return NOTES[pitch];if(mode==='degrees')return DEG[mod(pitch-root)];return ''}
function renderStrings(conf,set,root,mode){const strings=conf.tuning.length,frets=conf.frets,W=1580,H=90+78*(strings-1),svg=svgEl('svg');svg.id='fretboard';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);const bg=svgEl('rect');Object.entries({x:0,y:0,width:W,height:H,rx:14,fill:'#fff'}).forEach(([k,v])=>bg.setAttribute(k,v));svg.appendChild(bg);const left=45,top=35,cw=115,ch=78;for(let f=0;f<=frets;f++)svg.appendChild(line(left+cw*f,top,left+cw*f,top+ch*(strings-1),f===0?'#8b6f47':'#94a3b8',f===0?6:1.5));for(let s=0;s<strings;s++)svg.appendChild(line(left,top+ch*s,left+cw*(frets+1),top+ch*s,'#475569',1.8));[3,5,7,9,12].forEach(f=>svg.appendChild(circle(left+cw*(f-.5),top+ch*(strings-1)/2,5,'#cbd5e1')));for(let row=0;row<strings;row++){const open=NOTES.indexOf(conf.tuning[strings-1-row]);for(let f=0;f<=frets;f++){const pitch=mod(open+f);if(!set.has(pitch))continue;const x=left+cw*(f-.5),y=top+ch*row;svg.appendChild(circle(x,y,18,pitch===root?'#dc2626':'#f59e0b'));const lab=labelFor(pitch,root,mode);if(lab){const t=text(x,y,lab);t.setAttribute('fill','#111827');svg.appendChild(t)}}}for(let f=0;f<=frets;f++){const t=text(left+cw*f+7,H-18,String(f),13);t.setAttribute('fill','#64748b');svg.appendChild(t)}return svg}
function renderPiano(set,root,mode){const W=1500,H=360,whiteW=100,svg=svgEl('svg');svg.id='fretboard';svg.setAttribute('viewBox',`0 0 ${W} ${H}`);const whites=[0,2,4,5,7,9,11],blacks=[1,3,6,8,10],pos=[1,2,4,5,6];for(let o=0;o<2;o++)for(let i=0;i<7;i++){const p=whites[i],x=50+(o*7+i)*whiteW,r=svgEl('rect');Object.entries({x,y:35,width:whiteW,height:270,fill:set.has(p)?(p===root?'#ef4444':'#fbbf24'):'#fff',stroke:'#334155','stroke-width':2}).forEach(([k,v])=>r.setAttribute(k,v));svg.appendChild(r);const l=labelFor(p,root,mode);if(set.has(p)&&l)svg.appendChild(text(x+50,255,l,18))}for(let o=0;o<2;o++)for(let i=0;i<5;i++){const p=blacks[i],x=50+(o*7+pos[i])*whiteW-32,r=svgEl('rect');Object.entries({x,y:35,width:64,height:165,rx:4,fill:set.has(p)?(p===root?'#ef4444':'#f59e0b'):'#111827'}).forEach(([k,v])=>r.setAttribute(k,v));svg.appendChild(r);const l=labelFor(p,root,mode);if(set.has(p)&&l){const t=text(x+32,135,l,14);t.setAttribute('fill','#fff');svg.appendChild(t)}}return svg}
function renderTable(v,r){$('#scaleTable').innerHTML='<table class="table"><thead><tr><th>区分</th><th>度数</th><th>音名</th><th>半音差</th></tr></thead><tbody>'+v.map(x=>`<tr><td><span class="badge ${x===0?'badge-root':'badge-scale'}">${x===0?'ルート':'スケール'}</span></td><td>${DEG[x]}</td><td>${NOTES[mod(r+x)]}</td><td>${x}</td></tr>`).join('')+'</tbody></table>'}
function render(){const inst=INST[$('#instrumentSelect').value],root=NOTES.indexOf($('#keySelect').value),vals=selected(),set=new Set(vals.map(v=>mod(root+v))),mode=$('#displayMode').value,svg=inst===INST.piano?renderPiano(set,root,mode):renderStrings(inst,set,root,mode);$('#fretboard').replaceWith(svg);svg.onclick=openZoom;$('#instrumentBadge').textContent=`${inst.icon} ${inst.name}`;$('#instrumentInfo').textContent=inst.info+' / スマホ対応';renderTable(vals,root)}
function openZoom(){const z=$('#zoomOverlay'),stage=$('#zoomStage');stage.innerHTML='';const c=$('#fretboard').cloneNode(true);c.removeAttribute('id');c.style.width=c.style.height='100%';stage.appendChild(c);$('#zoomInfoLabel').textContent=`${INST[$('#instrumentSelect').value].name}｜${$('#keySelect').value}｜${$('#scaleSelect').value}`;z.hidden=false;document.body.style.overflow='hidden';z.onclick=()=>{z.hidden=true;document.body.style.overflow=''}}
function download(){const s=new XMLSerializer().serializeToString($('#fretboard')),u=URL.createObjectURL(new Blob([s],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas'),vb=$('#fretboard').viewBox.baseVal;c.width=vb.width*2;c.height=vb.height*2;const x=c.getContext('2d');x.scale(2,2);x.drawImage(img,0,0);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${$('#instrumentSelect').value}_${$('#keySelect').value}_${$('#scaleSelect').value}.png`;a.click()});URL.revokeObjectURL(u)};img.src=u}
function theory(){const v=selected();$('#theoryBody').innerHTML=`<div class="row"><span class="label">楽器</span><span class="value">${INST[$('#instrumentSelect').value].name}</span></div><div class="row"><span class="label">キー</span><span class="value">${$('#keySelect').value}</span></div><div class="row"><span class="label">スケール</span><span class="value">${$('#scaleSelect').value}</span></div><div class="row"><span class="label">構成</span><span class="value">${v.map(x=>DEG[x]).join(' ')}</span></div>`;$('#theoryModal').hidden=false}
function init(){initOptions();['instrumentSelect','keySelect','genreSelect','scaleSelect','displayMode'].forEach(id=>$('#'+id).addEventListener('change',()=>{if(id==='genreSelect')fillScales();render()}));$$('.tension').forEach(x=>x.onchange=render);$('#tensionClearBtn').onclick=()=>{$$('.tension').forEach(x=>x.checked=false);render()};$('#downloadBtn').onclick=download;$('#theoryBtn').onclick=theory;$('#theoryClose').onclick=()=>$('#theoryModal').hidden=true;render()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();